Vagrant.configure("2") do |config|


    config.vm.define "dev" do |dev|
      dev.vm.box = "bento/ubuntu-20.04"
      dev.vm.hostname = "dev"
      dev.vm.network "private_network", ip: "192.168.56.41"
      dev.vm.network "forwarded_port", guest: 80, host: 5050
  
      dev.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 2048
      end
    end
  
  
    config.vm.define "staging" do |staging|
      staging.vm.box = "bento/ubuntu-20.04"
      staging.vm.hostname = "staging"
      staging.vm.network "private_network", ip: "192.168.56.42"
      staging.vm.network "forwarded_port", guest: 80, host: 5051
  
      staging.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 2048
      end
    end
  
    config.vm.define "prod" do |prod|
      prod.vm.box = "bento/ubuntu-20.04"
      prod.vm.hostname = "prod"
      prod.vm.network "private_network", ip: "192.168.56.43"
      prod.vm.network "forwarded_port", guest: 80, host: 50512
  
      prod.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 2048
      end
    end
  
  end